### ISSUE TITLE
How to import libs to my gradle?

### ISSUE THREAD

**Issue by jackyhieu1211-hn** [epam/CoroutinesExtensions#1]
Hello admin. 
How to import libs to my gradle? 
Thanks you

**Comment by volodia-chornenkyy** [comment]
Hi @hieuseesaa, you have 2 options to accomplish this:

1. Copy file with extensions directly from [sources](https://github.com/epam/CoroutinesExtensions/tree/master/coroutinesoperators/src/main/java/com/epam/coroutinesextensions/coroutinesoperators)
2. Clone the repo and add **coroutinesoperators** module as an Android module to the project.

In the near future, the library will be available via Gradle dependencies.

**Comment by jackyhieu1211-hn** [comment]
Thanks you
